git rm 50-labels-graphs.ipynb
git rm FilesIndex.txt
git rm GPT2-dataframe-building-and-training.ipynb
git rm GPT2SummarizerDataframeBuilder.py
git rm ModelTrainPipeline.ipynb
git rm build-llama-dataframe.ipynb
git rm eurovoc-info.txt
git rm git_globals.sh
git rm gpt2-graphs.ipynb
git rm install_sw.sh
git rm labels-graphs-by-intervals.ipynb
git rm process-GPT2-training-session-data.ipynb
git rm reduced-model-1-graphs.ipynb
git rm session_init.sh
git rm tfm_50LabelsBertEURLEX57KDataFrameBuilder.py
git rm tfm_50LabelsDataFrameBuilderBase.py
git rm tfm_50LabelsDeepSeekEURLEX57KDataFrameBuilder.py
git rm tfm_50LabelsEURLEX57KBuilder.py
git rm tfm_50LabelsEURLEX57KDataFrameBuilder.py
git rm tfm_50LabelsGPT2DataFrameBuilder.py
git rm tfm_50LabelsLabelIndex.py
git rm tfm_BERTTokensBuilder.py
git rm tfm_BERTUtils.py
git rm tfm_CreateFileIndices.py
git rm tfm_CreateLabelIndex.py
git rm tfm_DatasetAnalyzer.py
git rm tfm_DeepSeekTokensBuilder.py
git rm tfm_EURLEX57KDataFrameBuilder.py
git rm tfm_EURLEX57KDataset.py
git rm tfm_EURLEX57KMainBodyLinesGenerator.py
git rm tfm_GPT2TokensBuilder.py
git rm tfm_LabelIndex.py
git rm tfm_LabelLoader.py
git rm tfm_Llama33TokensBuilder.py
git rm tfm_ModelTokensBuilder.py
git rm tfm_ModelTrainPipeline.py
git rm tfm_Pipeline.py
git rm tfm_ReducedDatasetAnalyzer.py
git rm tfm_ReducedDatasetBuilder.py
git rm tfm_ReducedDatasetBuilderV2.py
git rm tfm_ReducedEURLEX57KDataFrameBuilder.py
git rm tfm_ReducedLabelIndex.py
git rm tfm_muecim.ipynb
git rm tfm_www/demo-flask-app.py
git rm tfm_www/static/bootstrap/dist/css/.DS_Store
git rm tfm_www/static/bootstrap/dist/css/bootstrap-grid.css
git rm tfm_www/static/bootstrap/dist/css/bootstrap-grid.css.map
git rm tfm_www/static/bootstrap/dist/css/bootstrap-grid.min.css
git rm tfm_www/static/bootstrap/dist/css/bootstrap-grid.min.css.map
git rm tfm_www/static/bootstrap/dist/css/bootstrap-grid.rtl.css
git rm tfm_www/static/bootstrap/dist/css/bootstrap-grid.rtl.css.map
git rm tfm_www/static/bootstrap/dist/css/bootstrap-grid.rtl.min.css
git rm tfm_www/static/bootstrap/dist/css/bootstrap-grid.rtl.min.css.map
git rm tfm_www/static/bootstrap/dist/css/bootstrap-reboot.css
git rm tfm_www/static/bootstrap/dist/css/bootstrap-reboot.css.map
git rm tfm_www/static/bootstrap/dist/css/bootstrap-reboot.min.css
git rm tfm_www/static/bootstrap/dist/css/bootstrap-reboot.min.css.map
git rm tfm_www/static/bootstrap/dist/css/bootstrap-reboot.rtl.css
git rm tfm_www/static/bootstrap/dist/css/bootstrap-reboot.rtl.css.map
git rm tfm_www/static/bootstrap/dist/css/bootstrap-reboot.rtl.min.css
git rm tfm_www/static/bootstrap/dist/css/bootstrap-reboot.rtl.min.css.map
git rm tfm_www/static/bootstrap/dist/css/bootstrap-utilities.css
git rm tfm_www/static/bootstrap/dist/css/bootstrap-utilities.css.map
git rm tfm_www/static/bootstrap/dist/css/bootstrap-utilities.min.css
git rm tfm_www/static/bootstrap/dist/css/bootstrap-utilities.min.css.map
git rm tfm_www/static/bootstrap/dist/css/bootstrap-utilities.rtl.css
git rm tfm_www/static/bootstrap/dist/css/bootstrap-utilities.rtl.css.map
git rm tfm_www/static/bootstrap/dist/css/bootstrap-utilities.rtl.min.css
git rm tfm_www/static/bootstrap/dist/css/bootstrap-utilities.rtl.min.css.map
git rm tfm_www/static/bootstrap/dist/css/bootstrap.css
git rm tfm_www/static/bootstrap/dist/css/bootstrap.css.map
git rm tfm_www/static/bootstrap/dist/css/bootstrap.min.css
git rm tfm_www/static/bootstrap/dist/css/bootstrap.min.css.map
git rm tfm_www/static/bootstrap/dist/css/bootstrap.rtl.css
git rm tfm_www/static/bootstrap/dist/css/bootstrap.rtl.css.map
git rm tfm_www/static/bootstrap/dist/css/bootstrap.rtl.min.css
git rm tfm_www/static/bootstrap/dist/css/bootstrap.rtl.min.css.map
git rm tfm_www/static/bootstrap/dist/js/bootstrap.bundle.js
git rm tfm_www/static/bootstrap/dist/js/bootstrap.bundle.js.map
git rm tfm_www/static/bootstrap/dist/js/bootstrap.bundle.min.js
git rm tfm_www/static/bootstrap/dist/js/bootstrap.bundle.min.js.map
git rm tfm_www/static/bootstrap/dist/js/bootstrap.esm.js
git rm tfm_www/static/bootstrap/dist/js/bootstrap.esm.js.map
git rm tfm_www/static/bootstrap/dist/js/bootstrap.esm.min.js
git rm tfm_www/static/bootstrap/dist/js/bootstrap.esm.min.js.map
git rm tfm_www/static/bootstrap/dist/js/bootstrap.js
git rm tfm_www/static/bootstrap/dist/js/bootstrap.js.map
git rm tfm_www/static/bootstrap/dist/js/bootstrap.min.js
git rm tfm_www/static/bootstrap/dist/js/bootstrap.min.js.map
git rm tfm_www/static/css/styles.css
git rm tfm_www/static/examples/album-rtl/index.html
git rm tfm_www/static/examples/album/index.html
git rm tfm_www/static/examples/assets/brand/bootstrap-logo-white.svg
git rm tfm_www/static/examples/assets/brand/bootstrap-logo.svg
git rm tfm_www/static/examples/assets/dist/css/bootstrap.min.css
git rm tfm_www/static/examples/assets/dist/css/bootstrap.min.css.map
git rm tfm_www/static/examples/assets/dist/css/bootstrap.rtl.min.css
git rm tfm_www/static/examples/assets/dist/css/bootstrap.rtl.min.css.map
git rm tfm_www/static/examples/assets/dist/js/bootstrap.bundle.min.js
git rm tfm_www/static/examples/assets/dist/js/bootstrap.bundle.min.js.map
git rm tfm_www/static/examples/assets/js/color-modes.js
git rm tfm_www/static/examples/badges/badges.css
git rm tfm_www/static/examples/badges/index.html
git rm tfm_www/static/examples/blog-rtl/index.html
git rm tfm_www/static/examples/blog/blog.css
git rm tfm_www/static/examples/blog/blog.rtl.css
git rm tfm_www/static/examples/blog/index.html
git rm tfm_www/static/examples/breadcrumbs/breadcrumbs.css
git rm tfm_www/static/examples/breadcrumbs/index.html
git rm tfm_www/static/examples/buttons/index.html
git rm tfm_www/static/examples/carousel-rtl/index.html
git rm tfm_www/static/examples/carousel/carousel.css
git rm tfm_www/static/examples/carousel/carousel.rtl.css
git rm tfm_www/static/examples/carousel/index.html
git rm tfm_www/static/examples/cheatsheet-rtl/index.html
git rm tfm_www/static/examples/cheatsheet/cheatsheet.css
git rm tfm_www/static/examples/cheatsheet/cheatsheet.js
git rm tfm_www/static/examples/cheatsheet/cheatsheet.rtl.css
git rm tfm_www/static/examples/cheatsheet/index.html
git rm tfm_www/static/examples/checkout-rtl/index.html
git rm tfm_www/static/examples/checkout/checkout.css
git rm tfm_www/static/examples/checkout/checkout.js
git rm tfm_www/static/examples/checkout/index.html
git rm tfm_www/static/examples/cover/cover.css
git rm tfm_www/static/examples/cover/index.html
git rm tfm_www/static/examples/dashboard-rtl/dashboard.js
git rm tfm_www/static/examples/dashboard-rtl/index.html
git rm tfm_www/static/examples/dashboard/dashboard.css
git rm tfm_www/static/examples/dashboard/dashboard.js
git rm tfm_www/static/examples/dashboard/dashboard.rtl.css
git rm tfm_www/static/examples/dashboard/index.html
git rm tfm_www/static/examples/dropdowns/dropdowns.css
git rm tfm_www/static/examples/dropdowns/index.html
git rm tfm_www/static/examples/features/features.css
git rm tfm_www/static/examples/features/index.html
git rm tfm_www/static/examples/features/unsplash-photo-1.jpg
git rm tfm_www/static/examples/features/unsplash-photo-2.jpg
git rm tfm_www/static/examples/features/unsplash-photo-3.jpg
git rm tfm_www/static/examples/footers/index.html
git rm tfm_www/static/examples/grid/grid.css
git rm tfm_www/static/examples/grid/index.html
git rm tfm_www/static/examples/headers/headers.css
git rm tfm_www/static/examples/headers/index.html
git rm tfm_www/static/examples/heroes/bootstrap-docs.png
git rm tfm_www/static/examples/heroes/bootstrap-themes.png
git rm tfm_www/static/examples/heroes/heroes.css
git rm tfm_www/static/examples/heroes/index.html
git rm tfm_www/static/examples/jumbotron/index.html
git rm tfm_www/static/examples/jumbotrons/index.html
git rm tfm_www/static/examples/jumbotrons/jumbotrons.css
git rm tfm_www/static/examples/list-groups/index.html
git rm tfm_www/static/examples/list-groups/list-groups.css
git rm tfm_www/static/examples/masonry/index.html
git rm tfm_www/static/examples/modals/index.html
git rm tfm_www/static/examples/modals/modals.css
git rm tfm_www/static/examples/navbar-bottom/index.html
git rm tfm_www/static/examples/navbar-fixed/index.html
git rm tfm_www/static/examples/navbar-fixed/navbar-fixed.css
git rm tfm_www/static/examples/navbar-static/index.html
git rm tfm_www/static/examples/navbar-static/navbar-static.css
git rm tfm_www/static/examples/navbars-offcanvas/index.html
git rm tfm_www/static/examples/navbars-offcanvas/navbars-offcanvas.css
git rm tfm_www/static/examples/navbars/index.html
git rm tfm_www/static/examples/navbars/navbars.css
git rm tfm_www/static/examples/offcanvas-navbar/index.html
git rm tfm_www/static/examples/offcanvas-navbar/offcanvas-navbar.css
git rm tfm_www/static/examples/offcanvas-navbar/offcanvas-navbar.js
git rm tfm_www/static/examples/offcanvas/index.html
git rm tfm_www/static/examples/pricing/index.html
git rm tfm_www/static/examples/pricing/pricing.css
git rm tfm_www/static/examples/product/index.html
git rm tfm_www/static/examples/product/product.css
git rm tfm_www/static/examples/sidebars/index.html
git rm tfm_www/static/examples/sidebars/sidebars.css
git rm tfm_www/static/examples/sidebars/sidebars.js
git rm tfm_www/static/examples/sign-in/index.html
git rm tfm_www/static/examples/sign-in/sign-in.css
git rm tfm_www/static/examples/starter-template/index.html
git rm tfm_www/static/examples/sticky-footer-navbar/index.html
git rm tfm_www/static/examples/sticky-footer-navbar/sticky-footer-navbar.css
git rm tfm_www/static/examples/sticky-footer/index.html
git rm tfm_www/static/examples/sticky-footer/sticky-footer.css
git rm tfm_www/static/img/uoc-2-linies.png
git rm tfm_www/static/img/urv-2-linies.png
git rm tfm_www/static/img/urv-bandera-color.png
git rm tfm_www/static/img/urv-centrat-color.png
git rm tfm_www/static/index.html
git rm tfm_www/static/js/init.js
git rm tfm_www/static/js/messageBox.js
git rm tfm_www/static/js/tabs.js
git rm transform-eurlex57k-from-json-to-text.ipynb
